# Generated by Django 3.1.2 on 2020-10-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20201020_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='downloads_number',
            field=models.IntegerField(default=0),
        ),
    ]
