# Generated by Django 3.1.2 on 2020-10-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20201020_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
