# Generated by Django 3.1.2 on 2020-10-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_usersubscription_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
