# Generated by Django 3.1.2 on 2020-10-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20201021_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_partner', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('DOC', 'Documento'), ('PAR', 'Partitura'), ('LIB', 'Libro')], default='DOC', max_length=3),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, to='documents.Author'),
        ),
    ]
