# Generated by Django 3.1.2 on 2020-10-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20201022_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ManyToManyField(blank=True, to='documents.Author'),
        ),
    ]
