# Generated by Django 3.1.2 on 2020-10-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20201022_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='author',
            new_name='authors',
        ),
    ]
