# Generated by Django 3.1.2 on 2020-10-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20201022_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(default=2, to='documents.Author'),
        ),
    ]
