# Generated by Django 3.1.2 on 2020-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20201022_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='downloads_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='download',
            name='free_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('OK', 'Ok'), ('DN', 'Denied'), ('CN', 'Cancelled'), ('RF', 'Refounded')], max_length=2),
        ),
    ]
